Fix tcp output byte conversion
While running tcp output you encouter the following trace.

::

    tcp_writer.write( b"%s%s" % (msg, output_cfg["delimiter"]) )
    TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'

Parsing of sent messages looks good on a splunk server (Same parser used for
pdns-protobuf-receiver)